In [4]:
import numpy as np # array and vector manipulation
import pandas as pd # data manipulation
from sklearn.preprocessing import StandardScaler
import math

In [5]:
# loading our dataset: biodiversity project
# paper: https://doi.org/10.1080/0952813X.2021.1871972
# full dataset: https://data.mendeley.com/datasets/9x62992sw6/2
data_teste = pd.read_csv('biodiversity-br.csv')
data_teste

,alt,temp2m,temp2mrange,humidity,precip,atm,wind,m.fapar,classe
0,0.361674,0.719384,0.719384,0.614403,0.594679,0.979630,0.192118,0.665940,0
1,0.067043,0.916464,0.916464,0.579856,0.516432,0.994444,0.170624,0.365190,0
2,0.039864,0.856448,0.856448,0.818496,0.624413,1.000000,0.123337,0.798657,0
3,0.064889,0.821573,0.821573,0.872974,0.632238,1.000000,0.173509,0.999390,0
4,0.025681,0.788321,0.788321,1.000000,0.871674,1.000000,0.283287,0.896407,0
...,...,...,...,...,...,...,...,...,...
860,0.118726,0.142741,0.142741,0.707414,0.397496,0.112963,0.250426,0.623997,0
861,0.014968,0.197891,0.197891,0.718044,0.369327,0.112963,0.252041,0.455267,1
862,0.129396,0.142741,0.142741,0.680308,0.367762,0.061111,0.242492,0.627834,0
863,0.000000,0.213301,0.213301,0.712463,0.350548,0.061111,0.240703,0.397279,0
864,0.009390,0.114355,0.114355,0.750731,0.345853,0.000000,0.236029,0.349756,0

In [6]:
# creating our version of euclidean distance

def euclidean_distance(x, y):
    return np.sqrt(np.sum(pow((x - y), 2)))

In [7]:
# a simple KNN version 

def knn(train, test, label_idx = 8, k = 1):
    distances = np.zeros(train.shape[0])
    for i in np.arange(train.shape[0]):
        distances[i] = euclidean_distance(train.iloc[i, 0:label_idx], test[0:label_idx])
       
    return (np.argsort(distances)[0:k])

In [8]:
# selecting an instance to be used as test
train = data_teste
index_test = 4
teste = train.iloc[index_test]

In [9]:
# removing it from the dataset
train.drop(train.index[[index_test]], inplace = True)
train

,alt,temp2m,temp2mrange,humidity,precip,atm,wind,m.fapar,classe
0,0.361674,0.719384,0.719384,0.614403,0.594679,0.979630,0.192118,0.665940,0
1,0.067043,0.916464,0.916464,0.579856,0.516432,0.994444,0.170624,0.365190,0
2,0.039864,0.856448,0.856448,0.818496,0.624413,1.000000,0.123337,0.798657,0
3,0.064889,0.821573,0.821573,0.872974,0.632238,1.000000,0.173509,0.999390,0
5,0.007400,0.847526,0.847526,0.855700,0.818466,1.000000,0.131243,0.793861,0
...,...,...,...,...,...,...,...,...,...
860,0.118726,0.142741,0.142741,0.707414,0.397496,0.112963,0.250426,0.623997,0
861,0.014968,0.197891,0.197891,0.718044,0.369327,0.112963,0.252041,0.455267,1
862,0.129396,0.142741,0.142741,0.680308,0.367762,0.061111,0.242492,0.627834,0
863,0.000000,0.213301,0.213301,0.712463,0.350548,0.061111,0.240703,0.397279,0
864,0.009390,0.114355,0.114355,0.750731,0.345853,0.000000,0.236029,0.349756,0

In [10]:
# running our knn
output = knn(train, teste, k=5)

In [11]:
# checking the nearest instantances
train.iloc[output]

,alt,temp2m,temp2mrange,humidity,precip,atm,wind,m.fapar,classe
26,0.045750,0.817518,0.817518,0.951900,0.940532,0.994444,0.268053,0.809121,1
20,0.046128,0.807786,0.807786,0.954026,0.996870,0.994444,0.253599,0.906348,0
16,0.046247,0.834550,0.834550,0.888121,0.790297,0.994444,0.266611,0.945239,1
6,0.026737,0.845093,0.845093,0.893170,0.784038,1.000000,0.265399,0.724538,1
40,0.022491,0.822384,0.822384,0.859421,0.724570,0.979630,0.170191,0.921870,1

# Usando sklearn

In [12]:
# loading the necessary functions
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [14]:
# creating train/test folds
y = data_teste['classe']
data_teste = data_teste.drop(['classe'], axis = 1)
X_train,X_test,y_train,y_test = train_test_split(data_teste, y, test_size=0.1, random_state=42, 
                                                 stratify=y, shuffle=True)

In [15]:
# setting the hyperparameter k=10
lazy = KNeighborsClassifier(n_neighbors = 10)

In [16]:
# start modeling the problem
# as this algorithm is lazy, the model is basically storing the KB
lazy.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [17]:
# lets check the performance of our model by classifying new examples
lazy.score(X_test, y_test)

0.5747126436781609

In [16]:
X_test.loc[571], y_test[571]

(alt            0.581665
 temp2m         0.414436
 temp2mrange    0.414436
 humidity       0.589158
 precip         0.367762
 atm            0.620370
 wind           0.135657
 m.fapar        0.511249
 Name: 571, dtype: float64,
 1)

In [19]:
lazy.predict(X_test.loc[[571]])

array([1])

In [21]:
lazy.predict_proba(X_test.loc[[571]])

array([[0.2, 0.8]])

In [ ]:
# Testando DTW
#Baixar os datasets em: https://www.sciencedirect.com/science/article/pii/S2352340920305217

In [22]:
# loading files
import h5py

filename = "/tmp/lp.hdf5"
with h5py.File(filename, "r") as f:
    # List all groups
    a_group_key = list(f.keys())[0]

    # Get the data
    data_lp = list(f[a_group_key])

In [23]:
filename = "/tmp/tc.hdf5"
with h5py.File(filename, "r") as f:
    # List all groups
    a_group_key = list(f.keys())[0]

    # Get the data
    data_tc = list(f[a_group_key])

In [24]:
from dtw import *

Importing the dtw module. When using in academic works please cite:
  T. Giorgino. Computing and Visualizing Dynamic Time Warping Alignments in R: The dtw Package.
  J. Stat. Soft., doi:10.18637/jss.v031.i07.

In [25]:
sample_size = 30

# criando um dataset com 30 instâncias do tipo lp, perceba que agora há um atributo de classe

signal_data = pd.DataFrame(np.reshape(np.array(data_lp), 
                                      (np.array(data_lp).shape[0], 
                                       np.array(data_lp).shape[1])))
signal_data["class"] = np.repeat(0, signal_data.shape[0])

data = signal_data.iloc[np.random.randint(low = 0, high = len(data_lp), 
                                          size = sample_size), :]
data

,0,1,2,3,4,5,6,7,8,9,...,5991,5992,5993,5994,5995,5996,5997,5998,5999,class
266,1.541107,1.529391,1.511290,1.494371,1.484862,1.483946,1.488952,1.496252,1.502232,1.504071,...,1.516840,1.516840,1.516840,1.516840,1.516840,1.516840,1.516840,1.516840,1.516840,0
1107,1.532277,1.511344,1.492086,1.479779,1.477336,1.484292,1.497531,1.512674,1.524980,1.530203,...,1.474235,1.474235,1.474235,1.474235,1.474235,1.474235,1.474235,1.474235,1.474235,0
271,1.428702,1.467138,1.507486,1.538948,1.552499,1.544449,1.517663,1.481001,1.447171,1.427151,...,1.511893,1.511893,1.511893,1.511893,1.511893,1.511893,1.511893,1.511893,1.511893,0
3,1.503953,1.504057,1.504445,1.505137,1.506073,1.507096,1.507952,1.508391,1.508331,1.507935,...,1.490446,1.490446,1.490446,1.490446,1.490446,1.490446,1.490446,1.490446,1.490446,0
209,1.646762,1.642947,1.632196,1.616761,1.599955,1.584902,1.572978,1.562973,1.551860,1.536918,...,1.544359,1.544359,1.544359,1.544359,1.544359,1.544359,1.544359,1.544359,1.544359,0
405,1.514378,1.516749,1.520820,1.524922,1.526761,1.524827,1.519280,1.511799,1.504609,1.499421,...,1.516562,1.516562,1.516562,1.516562,1.516562,1.516562,1.516562,1.516562,1.516562,0
297,1.499328,1.510574,1.520226,1.526764,1.530041,1.531568,1.533884,1.538962,1.547189,1.557338,...,1.548511,1.548511,1.548511,1.548511,1.548511,1.548511,1.548511,1.548511,1.548511,0
284,1.530143,1.500983,1.476480,1.461611,1.457117,1.460519,1.468270,1.477372,1.486091,1.493689,...,1.456996,1.456996,1.456996,1.456996,1.456996,1.456996,1.456996,1.456996,1.456996,0
176,1.498389,1.499466,1.502650,1.507088,1.511509,1.514796,1.516428,1.516579,1.515928,1.515308,...,1.511438,1.511438,1.511438,1.511438,1.511438,1.511438,1.511438,1.511438,1.511438,0
998,1.491979,1.488031,1.483810,1.479766,1.476113,1.472904,1.470120,1.467742,1.465793,1.464371,...,1.479380,1.479380,1.479380,1.479380,1.479380,1.479380,1.479380,1.479380,1.479380,0
570,1.537267,1.529657,1.519443,1.509555,1.502625,1.500949,1.505987,1.517314,1.531990,1.545262,...,1.522044,1.522044,1.522044,1.522044,1.522044,1.522044,1.522044,1.522044,1.522044,0
1201,1.519462,1.515389,1.511753,1.510403,1.512229,1.516661,1.521738,1.524922,1.524118,1.518287,...,1.481191,1.481191,1.481191,1.481191,1.481191,1.481191,1.481191,1.481191,1.481191,0
1145,1.574147,1.566541,1.555334,1.542027,1.529257,1.519974,1.516170,1.518040,1.524349,1.533694,...,1.548823,1.548823,1.548823,1.548823,1.548823,1.548823,1.548823,1.548823,1.548823,0
1205,1.525181,1.549492,1.564459,1.566115,1.556028,1.540337,1.526377,1.519061,1.519125,1.523864,...,1.515361,1.515361,1.515361,1.515361,1.515361,1.515361,1.515361,1.515361,1.515361,0
876,1.566125,1.586936,1.590155,1.575845,1.553074,1.531701,1.514160,1.493592,1.460651,1.414015,...,1.482063,1.482063,1.482063,1.482063,1.482063,1.482063,1.482063,1.482063,1.482063,0
245,1.333587,1.383224,1.456387,1.535398,1.601615,1.640983,1.647149,1.621813,1.573243,1.513740,...,1.488337,1.488337,1.488337,1.488337,1.488337,1.488337,1.488337,1.488337,1.488337,0
211,1.530481,1.535168,1.527220,1.509882,1.488260,1.467594,1.451924,1.443411,1.442371,1.447964,...,1.529490,1.529490,1.529490,1.529490,1.529490,1.529490,1.529490,1.529490,1.529490,0
683,1.571584,1.597782,1.620771,1.635364,1.637681,1.625474,1.597923,1.555914,1.502821,1.445034,...,1.506998,1.506998,1.506998,1.506998,1.506998,1.506998,1.506998,1.506998,1.506998,0
17,1.474473,1.486368,1.505322,1.530268,1.557641,1.581839,1.597204,1.600393,1.591752,1.575078,...,1.414953,1.414953,1.414953,1.414953,1.414953,1.414953,1.414953,1.414953,1.414953,0
1252,1.424922,1.433998,1.443707,1.451815,1.456461,1.456741,1.452782,1.445444,1.435812,1.424899,...,1.432557,1.432557,1.432557,1.432557,1.432557,1.432557,1.432557,1.432557,1.432557,0
1244,1.458178,1.470751,1.475787,1.471085,1.457385,1.438297,1.419199,1.405536,1.401227,1.407737,...,1.441366,1.441366,1.441366,1.441366,1.441366,1.441366,1.441366,1.441366,1.441366,0
737,1.497104,1.492344,1.484868,1.477513,1.473236,1.474380,1.482182,1.496488,1.515463,1.535404,...,1.459599,1.459599,1.459599,1.459599,1.459599,1.459599,1.459599,1.459599,1.459599,0
1132,1.492402,1.496680,1.503684,1.510562,1.514908,1.515654,1.513498,1.510582,1.509406,1.511578,...,1.518841,1.518841,1.518841,1.518841,1.518841,1.518841,1.518841,1.518841,1.518841,0
838,1.500299,1.500095,1.506799,1.515906,1.521960,1.521268,1.513530,1.501755,1.491006,1.486390,...,1.515136,1.515136,1.515136,1.515136,1.515136,1.515136,1.515136,1.515136,1.515136,0
467,1.496411,1.498613,1.499161,1.506170,1.524785,1.553085,1.582615,1.602998,1.607342,1.595225,...,1.483783,1.483783,1.483783,1.483783,1.483783,1.483783,1.483783,1.483783,1.483783,0
473,1.478257,1.488275,1.499649,1.508905,1.513290,1.511938,1.506300,1.499320,1.493900,1.491778,...,1.501890,1.501890,1.501890,1.501890,1.501890,1.501890,1.501890,1.501890,1.501890,0
972,1.464832,1.464558,1.464199,1.464503,1.465864,1.468059,1.470333,1.471878,1.472430,1.472583,...,1.478924,1.478924,1.478924,1.478924,1.478924,1.478924,1.478924,1.478924,1.478924,0
1021,1.452815,1.448105,1.441515,1.433613,1.425265,1.417501,1.411262,1.407166,1.405434,1.405973,...,1.433172,1.433172,1.433172,1.433172,1.433172,1.433172,1.433172,1.433172,1.433172,0
1174,1.527110,1.536781,1.546053,1.546185,1.535122,1.518213,1.503411,1.495984,1.496622,1.502451,...,1.515724,1.515724,1.515724,1.515724,1.515724,1.515724,1.515724,1.515724,1.515724,0
729,1.506061,1.481862,1.460146,1.445905,1.439942,1.439111,1.438674,1.434999,1.427201,1.417446,...,1.476423,1.476423,1.476423,1.476423,1.476423,1.476423,1.476423,1.476423,1.476423,0

In [26]:
# Anexando agora exemplos da classe tc (apenas 30 exemplos também para "prova de conceito")

signal_data = pd.DataFrame(np.reshape(np.array(data_tc), 
                                      (np.array(data_tc).shape[0], 
                                       np.array(data_tc).shape[1])))
signal_data["class"] = np.repeat(1, signal_data.shape[0])
data = pd.concat([data, signal_data.iloc[np.random.randint(low = 0, 
                                                           high = len(data_tc), 
                                                           size = sample_size), :]])
data

,0,1,2,3,4,5,6,7,8,9,...,5991,5992,5993,5994,5995,5996,5997,5998,5999,class
266,1.541107,1.529391,1.511290,1.494371,1.484862,1.483946,1.488952,1.496252,1.502232,1.504071,...,1.516840,1.516840,1.516840,1.516840,1.516840,1.516840,1.516840,1.516840,1.516840,0
1107,1.532277,1.511344,1.492086,1.479779,1.477336,1.484292,1.497531,1.512674,1.524980,1.530203,...,1.474235,1.474235,1.474235,1.474235,1.474235,1.474235,1.474235,1.474235,1.474235,0
271,1.428702,1.467138,1.507486,1.538948,1.552499,1.544449,1.517663,1.481001,1.447171,1.427151,...,1.511893,1.511893,1.511893,1.511893,1.511893,1.511893,1.511893,1.511893,1.511893,0
3,1.503953,1.504057,1.504445,1.505137,1.506073,1.507096,1.507952,1.508391,1.508331,1.507935,...,1.490446,1.490446,1.490446,1.490446,1.490446,1.490446,1.490446,1.490446,1.490446,0
209,1.646762,1.642947,1.632196,1.616761,1.599955,1.584902,1.572978,1.562973,1.551860,1.536918,...,1.544359,1.544359,1.544359,1.544359,1.544359,1.544359,1.544359,1.544359,1.544359,0
405,1.514378,1.516749,1.520820,1.524922,1.526761,1.524827,1.519280,1.511799,1.504609,1.499421,...,1.516562,1.516562,1.516562,1.516562,1.516562,1.516562,1.516562,1.516562,1.516562,0
297,1.499328,1.510574,1.520226,1.526764,1.530041,1.531568,1.533884,1.538962,1.547189,1.557338,...,1.548511,1.548511,1.548511,1.548511,1.548511,1.548511,1.548511,1.548511,1.548511,0
284,1.530143,1.500983,1.476480,1.461611,1.457117,1.460519,1.468270,1.477372,1.486091,1.493689,...,1.456996,1.456996,1.456996,1.456996,1.456996,1.456996,1.456996,1.456996,1.456996,0
176,1.498389,1.499466,1.502650,1.507088,1.511509,1.514796,1.516428,1.516579,1.515928,1.515308,...,1.511438,1.511438,1.511438,1.511438,1.511438,1.511438,1.511438,1.511438,1.511438,0
998,1.491979,1.488031,1.483810,1.479766,1.476113,1.472904,1.470120,1.467742,1.465793,1.464371,...,1.479380,1.479380,1.479380,1.479380,1.479380,1.479380,1.479380,1.479380,1.479380,0
570,1.537267,1.529657,1.519443,1.509555,1.502625,1.500949,1.505987,1.517314,1.531990,1.545262,...,1.522044,1.522044,1.522044,1.522044,1.522044,1.522044,1.522044,1.522044,1.522044,0
1201,1.519462,1.515389,1.511753,1.510403,1.512229,1.516661,1.521738,1.524922,1.524118,1.518287,...,1.481191,1.481191,1.481191,1.481191,1.481191,1.481191,1.481191,1.481191,1.481191,0
1145,1.574147,1.566541,1.555334,1.542027,1.529257,1.519974,1.516170,1.518040,1.524349,1.533694,...,1.548823,1.548823,1.548823,1.548823,1.548823,1.548823,1.548823,1.548823,1.548823,0
1205,1.525181,1.549492,1.564459,1.566115,1.556028,1.540337,1.526377,1.519061,1.519125,1.523864,...,1.515361,1.515361,1.515361,1.515361,1.515361,1.515361,1.515361,1.515361,1.515361,0
876,1.566125,1.586936,1.590155,1.575845,1.553074,1.531701,1.514160,1.493592,1.460651,1.414015,...,1.482063,1.482063,1.482063,1.482063,1.482063,1.482063,1.482063,1.482063,1.482063,0
245,1.333587,1.383224,1.456387,1.535398,1.601615,1.640983,1.647149,1.621813,1.573243,1.513740,...,1.488337,1.488337,1.488337,1.488337,1.488337,1.488337,1.488337,1.488337,1.488337,0
211,1.530481,1.535168,1.527220,1.509882,1.488260,1.467594,1.451924,1.443411,1.442371,1.447964,...,1.529490,1.529490,1.529490,1.529490,1.529490,1.529490,1.529490,1.529490,1.529490,0
683,1.571584,1.597782,1.620771,1.635364,1.637681,1.625474,1.597923,1.555914,1.502821,1.445034,...,1.506998,1.506998,1.506998,1.506998,1.506998,1.506998,1.506998,1.506998,1.506998,0
17,1.474473,1.486368,1.505322,1.530268,1.557641,1.581839,1.597204,1.600393,1.591752,1.575078,...,1.414953,1.414953,1.414953,1.414953,1.414953,1.414953,1.414953,1.414953,1.414953,0
1252,1.424922,1.433998,1.443707,1.451815,1.456461,1.456741,1.452782,1.445444,1.435812,1.424899,...,1.432557,1.432557,1.432557,1.432557,1.432557,1.432557,1.432557,1.432557,1.432557,0
1244,1.458178,1.470751,1.475787,1.471085,1.457385,1.438297,1.419199,1.405536,1.401227,1.407737,...,1.441366,1.441366,1.441366,1.441366,1.441366,1.441366,1.441366,1.441366,1.441366,0
737,1.497104,1.492344,1.484868,1.477513,1.473236,1.474380,1.482182,1.496488,1.515463,1.535404,...,1.459599,1.459599,1.459599,1.459599,1.459599,1.459599,1.459599,1.459599,1.459599,0
1132,1.492402,1.496680,1.503684,1.510562,1.514908,1.515654,1.513498,1.510582,1.509406,1.511578,...,1.518841,1.518841,1.518841,1.518841,1.518841,1.518841,1.518841,1.518841,1.518841,0
838,1.500299,1.500095,1.506799,1.515906,1.521960,1.521268,1.513530,1.501755,1.491006,1.486390,...,1.515136,1.515136,1.515136,1.515136,1.515136,1.515136,1.515136,1.515136,1.515136,0
467,1.496411,1.498613,1.499161,1.506170,1.524785,1.553085,1.582615,1.602998,1.607342,1.595225,...,1.483783,1.483783,1.483783,1.483783,1.483783,1.483783,1.483783,1.483783,1.483783,0
473,1.478257,1.488275,1.499649,1.508905,1.513290,1.511938,1.506300,1.499320,1.493900,1.491778,...,1.501890,1.501890,1.501890,1.501890,1.501890,1.501890,1.501890,1.501890,1.501890,0
972,1.464832,1.464558,1.464199,1.464503,1.465864,1.468059,1.470333,1.471878,1.472430,1.472583,...,1.478924,1.478924,1.478924,1.478924,1.478924,1.478924,1.478924,1.478924,1.478924,0
1021,1.452815,1.448105,1.441515,1.433613,1.425265,1.417501,1.411262,1.407166,1.405434,1.405973,...,1.433172,1.433172,1.433172,1.433172,1.433172,1.433172,1.433172,1.433172,1.433172,0
1174,1.527110,1.536781,1.546053,1.546185,1.535122,1.518213,1.503411,1.495984,1.496622,1.502451,...,1.515724,1.515724,1.515724,1.515724,1.515724,1.515724,1.515724,1.515724,1.515724,0
729,1.506061,1.481862,1.460146,1.445905,1.439942,1.439111,1.438674,1.434999,1.427201,1.417446,...,1.476423,1.476423,1.476423,1.476423,1.476423,1.476423,1.476423,1.476423,1.476423,0
490,1.421580,1.422327,1.422438,1.421824,1.420534,1.418772,1.416805,1.414872,1.413153,1.411809,...,1.348480,1.358718,1.372450,1.389679,1.409895,1.432196,1.455454,1.478450,1.499942,1
1469,1.549843,1.552468,1.547736,1.535920,1.518222,1.496858,1.475077,1.457088,1.447445,1.449661,...,1.517922,1.505293,1.498546,1.496856,1.497719,1.498289,1.496752,1.493031,1.488395,1
991,1.569384,1.574112,1.574170,1.569432,1.561444,1.553066,1.547193,1.545451,1.547705,1.552572,...,1.536938,1.530901,1.524903,1.523037,1.526965,1.535597,1.546692,1.558436,1.569468,1
81,1.513603,1.521220,1.527911,1.532936,1.534950,1.532380,1.524767,1.513862,1.503144,1.495777,...,1.478535,1.471974,1.465743,1.460602,1.457576,1.457441,1.459958,1.463728,1.466904,1
1087,1.407677,1.427383,1.452227,1.475684,1.491340,1.494430,1.484028,1.464324,1.443232,1.428904,...,1.467232,1.520523,1.601922,1.702346,1.807312,1.900601,1.967971,2.000000,1.993855,1
1276,1.511949,1.512019,1.512045,1.512031,1.512018,1.512065,1.512211,1.512460,1.512776,1.513107,...,1.537352,1.535019,1.530552,1.524871,1.519033,1.513976,1.510303,1.508168,1.507295,1
1438,1.448882,1.453548,1.449696,1.438500,1.422433,1.405046,1.390128,1.380449,1.376985,1.379105,...,1.426116,1.426116,1.426116,1.426116,1.426116,1.426116,1.426116,1.426116,1.426116,1
514,1.511702,1.511427,1.510994,1.510625,1.510568,1.510969,1.511799,1.512855,1.513858,1.514556,...,1.764121,1.727260,1.682453,1.632188,1.578948,1.524740,1.470999,1.418713,1.368609,1
434,1.584212,1.576508,1.563387,1.547243,1.530395,1.514617,1.500904,1.489548,1.480487,1.473769,...,1.513795,1.518584,1.519592,1.517109,1.511980,1.505421,1.498748,1.493137,1.489471,1
731,1.573732,1.576897,1.582033,1.588455,1.595052,1.600460,1.603452,1.603353,1.600246,1.594857,...,1.532974,1.528708,1.522565,1.515337,1.508141,1.502152,1.498314,1.497099,1.498426,1
1301,1.545777,1.545039,1.545293,1.546409,1.548043,1.549690,1.550820,1.551043,1.550248,1.548658,...,1.488752,1.398162,1.307717,1.223364,1.151266,1.097139,1.065406,1.058313,1.075304,1
1214,1.535557,1.504675,1.463617,1.422799,1.393938,1.385977,1.400745,1.431867,1.467608,1.495509,...,1.498480,1.478313,1.458938,1.442481,1.430920,1.426679,1.431212,1.443041,1.457116,1
1236,1.464751,1.461684,1.461132,1.462054,1.461650,1.459177,1.457873,1.462647,1.475392,1.492108,...,1.508287,1.500030,1.485312,1.467721,1.451842,1.441062,1.436337,1.436026,1.436681,1
1281,1.494518,1.501760,1.502765,1.497755,1.488527,1.477990,1.469288,1.464782,1.465447,1.470872,...,1.453690,1.435798,1.417691,1.402298,1.392308,1.389818,1.396121,1.411305,1.433862,1
71,1.542603,1.541446,1.539865,1.538171,1.536690,1.535572,1.534753,1.534103,1.533618,1.533488,...,1.713794,1.708724,1.705545,1.704842,1.706291,1.709191,1.712926,1.716843,1.719786,1
51,1.427159,1.424646,1.425190,1.427782,1.431098,1.433672,1.433923,1.430712,1.424331,1.416872,...,1.413388,1.399431,1.391572,1.391849,1.401074,1.417684,1.437243,1.453555,1.460897,1
1335,1.571404,1.572940,1.573846,1.573757,1.572554,1.570440,1.567939,1.565776,1.564653,1.564949,...,1.569558,1.565176,1.560166,1.555541,1.552192,1.550542,1.550428,1.551273,1.552484,1
22,1.560220,1.557417,1.555796,1.555910,1.558470,1.564306,1.573407,1.583674,1.590771,1.589975,...,1.463796,1.481001,1.505338,1.526046,1.537673,1.540739,1.538140,1.531686,1.521880,1
1191,1.459041,1.461323,1.462491,1.461339,1.458103,1.453849,1.449322,1.444448,1.438965,1.433454,...,1.569269,1.499554,1.417269,1.325655,1.232118,1.147118,1.082054,1.046675,1.046731,1
768,1.515703,1.514700,1.516143,1.519854,1.524967,1.530092,1.533684,1.534603,1.532635,1.528685,...,1.547329,1.552527,1.556240,1.557225,1.555312,1.551500,1.547647,1.545880,1.547901,1
750,1.574132,1.563110,1.558416,1.563572,1.579051,1.601120,1.622920,1.637293,1.639984,1.631446,...,1.517453,1.517453,1.517453,1.517453,1.517453,1.517453,1.517453,1.517453,1.517453,1
93,1.472559,1.466043,1.454874,1.442742,1.432946,1.427333,1.426248,1.429287,1.436170,1.447064,...,1.371681,1.365881,1.364804,1.368062,1.375075,1.385103,1.397081,1.409487,1.420515,1
894,1.535641,1.527247,1.520116,1.510511,1.500192,1.495988,1.503561,1.521182,1.539809,1.550010,...,1.446642,1.476333,1.503101,1.521762,1.527355,1.518763,1.501140,1.483802,1.474193,1
1406,1.523737,1.522656,1.521580,1.520564,1.519697,1.518944,1.518374,1.518384,1.519321,1.520753,...,1.729030,1.758625,1.791429,1.815483,1.817337,1.786919,1.720460,1.621698,1.501348,1
895,1.533305,1.540751,1.544868,1.544547,1.537331,1.522303,1.503124,1.487458,1.482169,1.488338,...,1.470349,1.476406,1.487271,1.496352,1.500697,1.503604,1.510829,1.524341,1.539929,1
1364,1.485005,1.478840,1.475811,1.476602,1.480446,1.485554,1.489793,1.491325,1.489194,1.483778,...,1.541515,1.524073,1.504507,1.482312,1.458431,1.434794,1.413083,1.393904,1.376699,1
53,1.619648,1.618556,1.617612,1.616217,1.614054,1.611396,1.608843,1.606768,1.605006,1.603059,...,1.628381,1.625846,1.623715,1.621824,1.619952,1.618064,1.616374,1.615288,1.615338,1
158,1.590826,1.597302,1.604357,1.610540,1.614068,1.613729,1.609474,1.602393,1.594219,1.586751,...,1.567445,1.567445,1.567445,1.567445,1.567445,1.567445,1.567445,1.567445,1.567445,1
1060,1.492033,1.491795,1.494084,1.498308,1.503057,1.506603,1.507785,1.506661,1.504446,1.502761,...,1.541372,1.534683,1.524801,1.513576,1.502961,1.494484,1.488972,1.486569,1.486858,1
833,1.510944,1.515320,1.519154,1.521563,1.522315,1.521769,1.520498,1.518949,1.517352,1.515872,...,1.517212,1.518012,1.516369,1.512534,1.507122,1.501016,1.495130,1.490128,1.486250,1

In [27]:
def distancia_dtw(x, y):
    return dtw(x, y).distance

In [28]:
lazy = KNeighborsClassifier(n_neighbors = 3, metric = distancia_dtw )